apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minikube-app
  template:
    metadata:
      labels:
        app: minikube-app
    spec:
      containers:
      - name: minikube-container
        image: vasanth31r/minikube-app:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 8080
